# Generated by Django 4.1.5 on 2023-08-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_title_product_tittle'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='products',
            field=models.ManyToManyField(through='carts.cartProducts', to='products.product'),
        ),
    ]
