# Generated by Django 4.1.5 on 2023-08-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_title_product_tittle'),
        ('carts', '0002_carts_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carts',
            name='products',
            field=models.ManyToManyField(through='carts.CartProducts', to='products.product'),
        ),
    ]
