# Generated by Django 4.1.5 on 2023-08-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_tittle_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='tittle',
        ),
    ]
